/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {
    public static void main(String[] args) {
        Graph graph = new Graph();

        Vertex vertex1 = graph.addVertex("B");
        Vertex vertex2 = graph.addVertex("A");
        Vertex vertex3 = graph.addVertex("C");

        graph.addEdge(vertex1, vertex2 ,2);
        graph.addEdge(vertex2, vertex3,3);
        graph.addEdge(vertex2, vertex1);
        System.out.println("Vertices: " + graph.getVertices());
        System.out.println("Neighbors of vertex " + vertex2 + ": " + graph.getNeighbors((Vertex) vertex2));
        System.out.println("Graph size: " + graph.size());
}
}
