/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap;

import hashmap.TreeIntersection.TreeIntersection;

import java.util.ArrayList;

public class App {
    public static  ArrayList<ArrayList<String>> left_join(Hashtable<String, String>  a, Hashtable<String, String>  b){
        ArrayList<ArrayList<String>> t = new ArrayList<>();
    for(String x : a.keys()){
        ArrayList<String> one = new ArrayList<>();
        one.add(x);
        one.add(a.get(x));
        if(b.has(x))
        one.add(b.get(x));
        else
        one.add(null);
//        System.out.println(one);
        t.add(one);
    }
    return t;
    }

    public  String repeated_word(String d){
        d=  d.toLowerCase();
        d=d.replace(",", "");
        d=d.replace(".", "");
        String[] words = d.split(" ");
        Hashtable<String, Integer> h = new Hashtable<>();
        for(String x : words) {
            if(h.has(x)){
                System.out.println(x);
                return x;
            }
            else
                h.set(x, 1);
        }
//        System.out.println(h);
        return " ";
    }
    public static void main(String[] args) {


    }
}
