/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap;

import java.util.Locale;

public class App {

    public  String repeated_word(String d){
        d=  d.toLowerCase();
        d=d.replace(",", "");
        d=d.replace(".", "");
        String[] words = d.split(" ");
        Hashtable<String, Integer> h = new Hashtable<>();
        for(String x : words) {
            if(h.has(x)){
                System.out.println(x);
                return x;
            }
            else
                h.set(x, 1);
        }
//        System.out.println(h);
        return " ";
    }
    public static void main(String[] args) {

//        repeated_word ("Once upon a time, there was a brave princess who...");
//        repeated_word("It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...");;
//        repeated_word("It WAS the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...");

//        System.out.println( Entry);
    }
}
