/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package domain.sort;

import java.util.ArrayList;
import java.util.List;

public class App {

    public static void main(String[] args) {
        List <Movie> movies = new ArrayList<>();
        movies.add(new Movie("The Shawshank Redemption", 1994, List.of("Drama")));
        movies.add(new Movie("Fcrrest Gump", 1991, List.of("Adventure","Drama")));
        movies.add(new Movie("Fbrrest Gump", 1990, List.of("Adventure","Drama")));
        movies.add(new Movie("high school musical", 2015, List.of("Crime", "Drama")));
        movies.add(new Movie("Avatar", 2009, List.of("Action",  "Sci-Fi")));
        movies.add(new Movie("Harry potter", 2004, List.of("Sci-Fi", "Drama")));
        movies.add(new Movie("IRon Man", 2001, List.of("Sci-Fi", "Action")));
//   for(Movie movie : movies ){
//       System.out.println(movie.getTitle());}
   MovieSorter a = new MovieSorter();
//   a.sortByTitle(movies);
//   a.sortByYear(movies);
        for(Movie movie : a.sortByYear(movies) ){
            System.out.println(movie.getYear());
        }


//        movies.stream().forEach(movie -> System.out.println(movie.getTitle()));
    }
}
