/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class Main {


    public static void main(String[] args) {

            LinkedList ll = new LinkedList();
        LinkedList Nll = new LinkedList();
            System.out.println("helloo");


        ll.append(1);


        Nll.append(5);



//        System.out.println(ll.toString());

LinkedList F =  ll.ziplists(ll,Nll);
        System.out.println( F.toString());
        }
    }

