/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;


import static org.junit.jupiter.api.Assertions.assertArrayEquals;


class Cc36 {
    @Test void Cc36_BFS() {
    Graph graph = new Graph();
        Vertex Pandora = graph.addVertex("Pandora");
        Vertex Arendelle = graph.addVertex("Arendelle");
        Vertex Metroville = graph.addVertex("Metroville");
        Vertex Monstroplolis = graph.addVertex("Monstroplolis");
        Vertex Narnia = graph.addVertex("Narnia");
        Vertex Naboo = graph.addVertex("Naboo");
        graph.addEdge(Pandora,Arendelle);

        graph.addEdge(Arendelle,Metroville);
        graph.addEdge(Arendelle,Monstroplolis);

        graph.addEdge(Metroville,Monstroplolis);

        graph.addEdge(Metroville,Narnia);
        graph.addEdge(Metroville,Naboo);

        graph.addEdge(Monstroplolis,Naboo);
        graph.addEdge(Naboo,Narnia);

        List<String> expected = Arrays.asList("Pandora", "Arendelle", "Metroville", "Monstroplolis", "Narnia", "Naboo");
        List<Vertex> actualVertices = graph.bfs(Pandora);


        List<String> actual = actualVertices.stream().map(Vertex::getValue).collect(Collectors.toList());

        assertEquals(expected, actual);
    }
}
