/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;

import static graph.App.business_trip;
import static org.junit.jupiter.api.Assertions.assertEquals;

class Lab37 {
    @Test void test1() {

        Graph jordan= new Graph();
        jordan.addVertex("amman");
        jordan.addVertex("Mafraq");
        jordan.addVertex("Zarqa");
        jordan.addVertex("Madaba");
        jordan.addVertex("Aqaba");
        jordan.addVertex("Maan");
        jordan.addEdge("amman","Zarqa",15);
        jordan.addEdge("amman","Madaba",10);
        jordan.addEdge("amman","Maan",35);
        jordan.addEdge("Maan","Aqaba",5);
        jordan.addEdge("Zarqa","Mafraq",33);
        String[] trip1 = {"amman", "Aqaba"};
        System.out.println(business_trip(jordan,trip1));
        assertEquals(business_trip(jordan,trip1),null);
    }

    @Test void test2() {

        Graph jordan= new Graph();
        jordan.addVertex("amman");
        jordan.addVertex("Mafraq");
        jordan.addVertex("Zarqa");
        jordan.addVertex("Madaba");
        jordan.addVertex("Aqaba");
        jordan.addVertex("Maan");
        jordan.addEdge("amman","Zarqa",15);
        jordan.addEdge("amman","Madaba",10);
        jordan.addEdge("amman","Maan",35);
        jordan.addEdge("Maan","Aqaba",5);
        jordan.addEdge("Zarqa","Mafraq",33);
        String[] trip1 = {"Zarqa","amman","Maan", "Aqaba"};
        System.out.println(business_trip(jordan,trip1));
        assertEquals(business_trip(jordan,trip1),55);
    }


    @Test void test3() {
        Graph jordan= new Graph();
        jordan.addVertex("amman");
        jordan.addVertex("Mafraq");
        jordan.addVertex("Zarqa");
        jordan.addVertex("Madaba");
        jordan.addVertex("Aqaba");
        jordan.addVertex("Maan");
        jordan.addEdge("amman","Zarqa",15);
        jordan.addEdge("amman","Madaba",10);
        jordan.addEdge("amman","Maan",35);
        jordan.addEdge("Maan","Aqaba",5);
        jordan.addEdge("Zarqa","Mafraq",33);
        String[] trip1 = {"amman", "Maan","Aqaba"};
        System.out.println(business_trip(jordan,trip1));
        assertEquals(business_trip(jordan,trip1),40);
    }
}
