/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binary.tree;

public class App {

    public static void main(String[] args) {
        System.out.println("hello world");
        BinaryTree tree = new BinaryTree();
        tree.root = new Node(1);
        tree.root.left = new Node(2);
        tree.root.right = new Node(344);
        tree.root.left.left = new Node(4);
        tree.root.left.right = new Node(5);
        tree.root.left.right = new Node(42);
//tree.printInorder();
//        System.out.println();
//tree.printPostorder();
//        System.out.println();
//tree.printPreorder();
        System.out.println(tree.FindMaximumValue());

//        BinarySearchTree bt = new BinarySearchTree();
//        bt.add(7);
//        bt.add(3);
//        bt.add(2);
//        bt.add(5);
//        bt.add(10);
//        bt.add(12);
//        bt.printPreorder();
//        bt.Contains(6);

    }
}
