/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binary.tree;

public class App {

    public static void main(String[] args) {
        System.out.println("hello world");
        BinaryTree tree = new BinaryTree();
        tree.root = new Node(1);
        tree.root.left = new Node(2);
        tree.root.right = new Node(3);
        tree.root.left.left = new Node(4);
        tree.root.left.right = new Node(5);
//        tree.Inorder(tree.root);
//        System.out.println();
//        tree.Preorder(tree.root);
//      tree.Postorder(tree.root);
tree.printInorder();
        System.out.println();
tree.printPostorder();
        System.out.println();
tree.printPreorder();

        BinarySearchTree bt = new BinarySearchTree();
        bt.add(7);
        bt.add(3);
        bt.add(2);
        bt.add(5);
        bt.add(10);
        bt.add(12);
        bt.printPreorder();
        bt.Contains(6);

    }
}
